name: Validate bootc build and release

on:
  push:
    branches:
      - main

env:
  REGISTRY_USER: butler54
  REGISTRY_NAMESPACE: tempest-concorde
  IMAGE_REGISTRY: ghcr.io
  IMAGE: satisfactory


jobs:
  testbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - name: Download and decompress steam
      run: | 
        mkdir -p steam
        cd steam && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
          
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE }}"
        tags: latest prod ${{ github.sha }}
        containerfiles: |
          ./Containerfile
          
    - name: delete secrets
      if: always()
      run: rm -f auth.json
  release:
    runs-on: ubuntu-latest
    needs: testbuild
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.FG_PAT }}
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ secrets.FG_PAT }}