name: Build bootc container based on pr to latest

on:
  pull_request:
    branches:
      - main
env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: bootc-lighthouse
jobs:
  buildlatest:
    name: Build Bootc image with repo access

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.RH_REGISTRY_USER }} # service account
        password: ${{ secrets.RH_REGISTRY_PASSWORD }} # service accounts
        registry: registry.redhat.io

    - name: dump authfile
      run: |
        echo "${{ secrets.AUTHCRED }}" > auth.json
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}"
        tags: latest ${{ github.sha }}
        containerfiles: |
         ./Containerfile
    - name: delete secrets
      if: always()
      run: rm -f auth.json