# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Weekly bounce
on:
  schedule:
    - cron: '0 0 * * 0'  # runs weekly

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: bootc-lab

jobs:
  buildrelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get latest v* tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 --match "v*" || echo "v0.0.0")
        echo "Latest tag: $latest_tag"
        clean_version=${latest_tag#v}  # Remove leading 'v'
        echo "Clean version: $clean_version"
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT
        echo "VERSION=$clean_version" >> $GITHUB_OUTPUT
    - name: Checkout latest tag
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
        
    
    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.RH_REGISTRY_USER }} # service account
        password: ${{ secrets.RH_REGISTRY_PASSWORD }} # service accounts
        registry: registry.redhat.io
    - name: dump authfile
      run: |
        echo "${{ secrets.AUTHCRED }}" > auth.json
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}"
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }}
        containerfiles: |
          ./Containerfile
  
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0
    
    - name: push to registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE }}
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }} 
        registry: quay.io/${{ env.REGISTRY_USER }}
    
    - name: what would we sign
      run: podman image inspect --format '{{ .Digest }}' quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}
      
    - name: Sign image
      #run: cosign sign  --yes -a tag=${{ steps.parse_version.outputs.VERSION }} -a tag=prod -a tag=latest -a tag=${{ github.sha }} -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}@`podman image inspect --format '{{ .Digest }}' quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}`
      run: cosign sign  --yes -a tag=${{ steps.parse_version.outputs.VERSION }} -a tag=prod -a tag=latest -a tag=${{ github.sha }} -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}:prod
    - name: delete secrets
      if: always()
      run: rm -f auth.json